import CartProduct from "@/app/_Components/CartProduct/page";
import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Jewelery",
  description: "Generated by create next app",
};

interface Product {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    rate: number;
    count: number;
  };
}
export default async function Page() {
  const response = await fetch("https://fakestoreapi.com/products");
  const data: Product[] = await response.json();

  const jewelery: Product[] = data.filter(
    (item) => item.category === "jewelery"
  );

  return (
    <div className="mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8">
      <h2 className="text-2xl font-bold tracking-tight text-gray-900">
        jewelery
      </h2>
      <div className="mt-6 grid grid-cols-1 gap-x-6 gap-y-10 sm:grid-cols-2 lg:grid-cols-4 xl:gap-x-8">
        {jewelery?.map((product) => (
          <div key={product.id} className=" relative">
            <CartProduct
              image={product.image}
              title={product.title}
              rating={product.rating.rate}
              price={product.price}
            />
          </div>
        ))}
      </div>
    </div>
  );
}
