import React from "react";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Category",
  description: "Generated by create next app",
};

function page() {
  return <div></div>;
}

export default page;
