import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_Components/NavBar/page";
import ProductContextProvider from "./_Components/Context/productContext";

export const metadata: Metadata = {
  title: "home page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <ProductContextProvider>{children}</ProductContextProvider>
      </body>
    </html>
  );
}
