import { Metadata } from "next";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <section className="bg-gradient-to-b from-[#1c2230] to-[#2a3445]">
      <div className="container mx-auto px-4">
        <div className="element-center flex-col pt-[150px]">
          <div className="w-[750px] max-w-full">
            <Image
              src="/next.svg"
              alt="Landing image"
              width={750}
              height={500}
              className="h-fit w-full drop-shadow-lg"
            />
          </div>
          <div className="text-white text-center mt-8">
            <h1 className="text-[30px] md:text-[40px] mb-[15px] font-bold leading-tight">
              All your files in one secure location,
              <br />
              accessible anywhere.
            </h1>
            <p className="font-light text-lg px-[15px] md:w-[600px] max-w-full mx-auto leading-relaxed">
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Nulla at
              ea necessitatibus? Dicta nam rem vitae officiis placeat molestias
              maiores quasi autem recusandae labore pariatur quo.
            </p>
          </div>
          <a
            href="/"
            className="btn w-[280px] h-[60px] rounded-[30px] element-center text-white mt-10 font-medium bg-gradient-to-r from-blue-500 to-purple-600 hover:from-purple-600 hover:to-blue-500 shadow-lg transition-all duration-300"
          >
            Get Started
          </a>
        </div>
      </div>
      <div className="w-full h-[200px] mt-10">
        {/* Add a decorative background or image */}
        <div className="w-full h-full bg-gradient-to-r from-blue-500 to-purple-600 opacity-20"></div>
      </div>
    </section>
  );
}
