import { Metadata } from "next";

export const metadata: Metadata = {
  title: "home page",
  description: "Generated by create next app",
};

export default function page() {
  return <div className="">Home page</div>;
}
