import { Metadata } from "next";
import Image from "next/image";
import ProductsList from "./_Components/ProductsList";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function Page() {
  return (
    <section className="flex-grow">
      <div className="container mx-auto px-4">
        <div className="flex flex-col items-center pt-[150px]">
          <div className="w-full max-w-[750px]">
            <Image
              src="/ecommerce.webp"
              alt="Landing image"
              width={750}
              height={500}
              className="h-fit w-full drop-shadow-lg rounded-lg"
            />
          </div>
          <div className="text-blue-950 text-center mt-8">
            <h1 className="text-[30px] md:text-[40px] mb-5 font-bold leading-tight">
              All your favorite products, in one secure place,
              <br />
              accessible anytime, anywhere
            </h1>
            <p className="font-light text-lg px-4 md:w-[600px] max-w-full mx-auto leading-relaxed">
              Discover a wide range of products tailored to your needs. Shop
              with confidence, enjoy secure payments, and experience fast
              delivery, all from the comfort of your home.
            </p>
          </div>
          <a
            href="/products"
            className="btn w-[280px] h-[60px] rounded-[30px] flex items-center justify-center text-white mt-10 font-medium bg-gradient-to-r from-blue-950 to-purple-600 hover:from-purple-600 hover:to-blue-950 shadow-lg transition-all duration-300 mb-[50px]"
          >
            SHOP NOW
          </a>
        </div>
      </div>
    </section>
  );
}
